import { StyleSheet } from 'react-native'

export const appStyles = StyleSheet.create({
  card: {
    backgroundColor: '#151515',
    borderColor: '#2a2a2a',
    borderRadius: 8,
    borderWidth: 1,
    padding: 12,
  },
  screen: {
    backgroundColor: '#000000',
    flex: 1,
  },
  screenContent: {
    gap: 20,
    paddingHorizontal: 20,
    paddingVertical: 24,
  },
  stack: {
    gap: 12,
  },
  text: {
    color: '#f5f5f5',
    fontFamily: 'Ubuntu-Regular',
    fontSize: 15,
    lineHeight: 22,
  },
  textStrong: {
    color: '#ffffff',
    fontFamily: 'Ubuntu-Bold',
  },
  title: {
    color: '#ffffff',
    fontFamily: 'Ubuntu-Bold',
    fontSize: 22,
    letterSpacing: 0,
  },
  appShell: {
    flex: 1,
    gap: 14,
    paddingHorizontal: 10,
    paddingTop: 8,
  },
  topBar: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 48,
  },
  brand: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 4,
  },
  logoMark: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 8,
    height: 30,
    justifyContent: 'center',
    width: 30,
  },
  logoMarkText: {
    color: '#000000',
    fontFamily: 'Ubuntu-Bold',
    fontSize: 21,
    lineHeight: 25,
  },
  brandText: {
    color: '#ffffff',
    fontFamily: 'Ubuntu-Bold',
    fontSize: 22,
    letterSpacing: 0,
    lineHeight: 27,
  },
  walletPill: {
    alignItems: 'center',
    backgroundColor: '#151515',
    borderColor: '#2a2a2a',
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 7,
    minHeight: 40,
    paddingHorizontal: 11,
    paddingVertical: 6,
  },
  walletAvatar: {
    alignItems: 'center',
    borderRadius: 999,
    borderWidth: 2,
    height: 26,
    justifyContent: 'center',
    width: 26,
  },
  walletAvatarDot: {
    backgroundColor: 'rgba(255, 255, 255, 0.78)',
    borderRadius: 999,
    height: 8,
    width: 8,
  },
  walletAddress: {
    color: '#ffffff',
    fontFamily: 'Ubuntu-Medium',
    fontSize: 12,
    letterSpacing: 0,
    lineHeight: 18,
  },
  walletConnectText: {
    color: '#ffffff',
    fontFamily: 'Ubuntu-Bold',
    fontSize: 11,
    letterSpacing: 0.8,
    lineHeight: 16,
  },
  poolList: {
    gap: 16,
    paddingBottom: 24,
    paddingTop: 2,
  },
  poolCard: {
    backgroundColor: '#090909',
    borderColor: '#262626',
    borderRadius: 22,
    borderWidth: 1,
    minHeight: 146,
    padding: 14,
    position: 'relative',
  },
  poolCardPressed: {
    opacity: 0.82,
    transform: [{ scale: 0.99 }],
  },
  poolLogo: {
    alignItems: 'center',
    backgroundColor: '#111111',
    borderRadius: 18,
    borderWidth: 1,
    height: 62,
    justifyContent: 'center',
    left: 14,
    position: 'absolute',
    top: 18,
    width: 62,
  },
  poolLogoText: {
    fontFamily: 'Ubuntu-Bold',
    fontSize: 32,
    lineHeight: 38,
  },
  poolLogoImage: {
    height: 42,
    resizeMode: 'contain',
    width: 42,
  },
  poolCardContent: {
    alignItems: 'center',
    gap: 12,
    paddingLeft: 82,
    paddingRight: 6,
    paddingTop: 12,
  },
  poolCardTitle: {
    color: '#f1f1f1',
    fontFamily: 'Ubuntu-Bold',
    fontSize: 23,
    letterSpacing: 0,
    lineHeight: 29,
    textAlign: 'center',
  },
  poolCardTime: {
    color: '#ffffff',
    fontFamily: 'Ubuntu-Regular',
    fontSize: 22,
    lineHeight: 28,
    textAlign: 'center',
  },
  poolCardFooter: {
    alignItems: 'flex-end',
    bottom: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
    left: 14,
    position: 'absolute',
    right: 14,
  },
  poolCardPrice: {
    color: '#d8d8d8',
    flex: 1,
    fontFamily: 'Ubuntu-Regular',
    fontSize: 14,
    lineHeight: 18,
    paddingRight: 8,
  },
  tickItButton: {
    alignItems: 'center',
    borderColor: '#e8e8e8',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 34,
    minWidth: 92,
    paddingHorizontal: 14,
  },
  tickItButtonText: {
    color: '#ffffff',
    fontFamily: 'Ubuntu-Bold',
    fontSize: 18,
    lineHeight: 23,
  },
  poolDetail: {
    gap: 14,
  },
  backButton: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: '#151515',
    borderColor: '#2a2a2a',
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 4,
    minHeight: 38,
    paddingLeft: 9,
    paddingRight: 13,
  },
  backButtonText: {
    color: '#ffffff',
    fontFamily: 'Ubuntu-Bold',
    fontSize: 11,
    letterSpacing: 0.8,
    lineHeight: 16,
  },
  poolHeader: {
    backgroundColor: '#070707',
    borderColor: '#151515',
    borderRadius: 0,
    borderWidth: 1,
    flexDirection: 'row',
    height: 58,
    overflow: 'hidden',
    position: 'relative',
  },
  poolSide: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 7,
    paddingHorizontal: 10,
  },
  poolSideRight: {
    justifyContent: 'flex-end',
    paddingRight: 16,
  },
  poolDivider: {
    backgroundColor: '#2a2a2a',
    height: '100%',
    width: 1,
  },
  poolAsset: {
    color: '#55555b',
    fontFamily: 'Ubuntu-Bold',
    fontSize: 13,
    letterSpacing: 1.2,
    lineHeight: 18,
  },
  poolPrice: {
    color: '#ff9d17',
    fontFamily: 'Ubuntu-Bold',
    fontSize: 23,
    letterSpacing: 0,
    lineHeight: 28,
  },
  poolPredictLabel: {
    color: '#68686f',
    fontFamily: 'Ubuntu-Bold',
    fontSize: 12,
    letterSpacing: 1.3,
    lineHeight: 17,
  },
  poolTimer: {
    color: '#b8ff66',
    fontFamily: 'Ubuntu-Bold',
    fontSize: 23,
    letterSpacing: 0,
    lineHeight: 28,
  },
  poolAccent: {
    backgroundColor: '#211a34',
    height: '120%',
    position: 'absolute',
    right: -10,
    top: -6,
    transform: [{ skewX: '5deg' }],
    width: 20,
  },
  poolDetailBody: {
    alignItems: 'center',
    backgroundColor: '#090909',
    borderColor: '#262626',
    borderRadius: 22,
    borderWidth: 1,
    gap: 14,
    paddingHorizontal: 18,
    paddingVertical: 28,
  },
  poolLogoLarge: {
    alignItems: 'center',
    backgroundColor: '#111111',
    borderRadius: 24,
    borderWidth: 1,
    height: 86,
    justifyContent: 'center',
    width: 86,
  },
  poolLogoLargeText: {
    fontFamily: 'Ubuntu-Bold',
    fontSize: 44,
    lineHeight: 52,
  },
  poolLogoLargeImage: {
    height: 60,
    resizeMode: 'contain',
    width: 60,
  },
  poolDetailTitle: {
    color: '#ffffff',
    fontFamily: 'Ubuntu-Bold',
    fontSize: 26,
    lineHeight: 32,
    textAlign: 'center',
  },
  poolDetailMeta: {
    color: '#cfcfcf',
    fontFamily: 'Ubuntu-Regular',
    fontSize: 17,
    lineHeight: 23,
    textAlign: 'center',
  },
  sheetBackdrop: {
    backgroundColor: 'rgba(0, 0, 0, 0.62)',
    flex: 1,
    justifyContent: 'flex-end',
  },
  walletSheet: {
    backgroundColor: '#111111',
    borderColor: '#2a2a2a',
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    borderWidth: 1,
    gap: 12,
    paddingBottom: 28,
    paddingHorizontal: 18,
    paddingTop: 10,
  },
  sheetHandle: {
    alignSelf: 'center',
    backgroundColor: '#4b4b4b',
    borderRadius: 999,
    height: 4,
    marginBottom: 6,
    width: 44,
  },
  sheetTitle: {
    color: '#ffffff',
    fontFamily: 'Ubuntu-Bold',
    fontSize: 20,
    letterSpacing: 0,
    lineHeight: 26,
  },
  fullAddress: {
    backgroundColor: '#191919',
    borderColor: '#2f2f2f',
    borderRadius: 8,
    borderWidth: 1,
    color: '#e6e6e6',
    fontFamily: 'Ubuntu-Regular',
    fontSize: 13,
    lineHeight: 19,
    padding: 12,
  },
  sheetAction: {
    alignItems: 'center',
    backgroundColor: '#1c1c1c',
    borderColor: '#303030',
    borderRadius: 8,
    borderWidth: 1,
    minHeight: 46,
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  sheetActionPrimary: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 8,
    flexDirection: 'row',
    gap: 8,
    minHeight: 48,
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  sheetActionPrimaryText: {
    color: '#000000',
    fontFamily: 'Ubuntu-Bold',
    fontSize: 14,
    letterSpacing: 0.8,
  },
  sheetActionText: {
    color: '#ffffff',
    fontFamily: 'Ubuntu-Bold',
    fontSize: 15,
    letterSpacing: 0,
  },
  sheetActionDanger: {
    alignItems: 'center',
    backgroundColor: '#2a1010',
    borderColor: '#5f2020',
    borderRadius: 8,
    borderWidth: 1,
    minHeight: 46,
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  sheetActionDangerText: {
    color: '#ff8f8f',
    fontFamily: 'Ubuntu-Bold',
    fontSize: 15,
    letterSpacing: 0,
  },
  sheetBodyText: {
    color: '#c8c8c8',
    fontFamily: 'Ubuntu-Regular',
    fontSize: 14,
    lineHeight: 20,
  },
  button: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 44,
    paddingHorizontal: 18,
    paddingVertical: 11,
  },
  buttonDisabled: {
    backgroundColor: '#333333',
  },
  buttonPressed: {
    opacity: 0.78,
    transform: [{ scale: 0.98 }],
  },
  buttonText: {
    color: '#000000',
    fontFamily: 'Ubuntu-Bold',
    fontSize: 15,
    letterSpacing: 0,
    lineHeight: 20,
  },
  buttonTextDisabled: {
    color: '#8f8f8f',
  },
  splash: {
    alignItems: 'center',
    backgroundColor: '#000000',
    flex: 1,
    justifyContent: 'center',
  },
  splashWord: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  splashLogoMark: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 12,
    height: 56,
    justifyContent: 'center',
    width: 56,
  },
  splashLogoMarkText: {
    color: '#000000',
    fontFamily: 'Ubuntu-Bold',
    fontSize: 42,
    lineHeight: 48,
  },
  splashIckReveal: {
    overflow: 'hidden',
  },
  splashIck: {
    color: '#ffffff',
    fontFamily: 'Ubuntu-Bold',
    fontSize: 56,
    letterSpacing: 0,
    lineHeight: 64,
  },
})
