import { StyleSheet } from 'react-native'

export const appStyles = StyleSheet.create({
  card: {
    backgroundColor: '#151515',
    borderColor: '#2a2a2a',
    borderRadius: 8,
    borderWidth: 1,
    padding: 12,
  },
  screen: {
    backgroundColor: '#000000',
    flex: 1,
  },
  screenContent: {
    gap: 20,
    paddingHorizontal: 20,
    paddingVertical: 24,
  },
  stack: {
    gap: 12,
  },
  text: {
    color: '#f5f5f5',
    fontFamily: 'Ubuntu-Regular',
    fontSize: 15,
    lineHeight: 22,
  },
  textStrong: {
    color: '#ffffff',
    fontFamily: 'Ubuntu-Bold',
  },
  title: {
    color: '#ffffff',
    fontFamily: 'Ubuntu-Bold',
    fontSize: 22,
    letterSpacing: 0,
  },
  appShell: {
    flex: 1,
    gap: 14,
    paddingHorizontal: 10,
    paddingTop: 8,
  },
  topBar: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 48,
  },
  brand: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 4,
  },
  logoMark: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 8,
    height: 30,
    justifyContent: 'center',
    width: 30,
  },
  logoMarkText: {
    color: '#000000',
    fontFamily: 'Ubuntu-Bold',
    fontSize: 21,
    lineHeight: 25,
  },
  brandText: {
    color: '#ffffff',
    fontFamily: 'Ubuntu-Bold',
    fontSize: 22,
    letterSpacing: 0,
    lineHeight: 27,
  },
  walletPill: {
    alignItems: 'center',
    backgroundColor: '#151515',
    borderColor: '#2a2a2a',
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 7,
    minHeight: 40,
    paddingHorizontal: 11,
    paddingVertical: 6,
  },
  walletAvatar: {
    alignItems: 'center',
    borderRadius: 999,
    borderWidth: 2,
    height: 26,
    justifyContent: 'center',
    width: 26,
  },
  walletAvatarDot: {
    backgroundColor: 'rgba(255, 255, 255, 0.78)',
    borderRadius: 999,
    height: 8,
    width: 8,
  },
  walletAddress: {
    color: '#ffffff',
    fontFamily: 'Ubuntu-Medium',
    fontSize: 12,
    letterSpacing: 0,
    lineHeight: 18,
  },
  walletConnectText: {
    color: '#ffffff',
    fontFamily: 'Ubuntu-Bold',
    fontSize: 11,
    letterSpacing: 0.8,
    lineHeight: 16,
  },
  poolList: {
    gap: 16,
    paddingBottom: 24,
    paddingTop: 2,
  },
  poolCard: {
    backgroundColor: '#090909',
    borderColor: '#262626',
    borderRadius: 22,
    borderWidth: 1,
    minHeight: 146,
    padding: 14,
    position: 'relative',
  },
  poolCardPressed: {
    opacity: 0.82,
    transform: [{ scale: 0.99 }],
  },
  poolLogo: {
    alignItems: 'center',
    backgroundColor: '#111111',
    borderRadius: 18,
    borderWidth: 1,
    height: 62,
    justifyContent: 'center',
    left: 14,
    position: 'absolute',
    top: 18,
    width: 62,
  },
  poolLogoText: {
    fontFamily: 'Ubuntu-Bold',
    fontSize: 32,
    lineHeight: 38,
  },
  poolLogoImage: {
    height: 42,
    resizeMode: 'contain',
    width: 42,
  },
  poolCardContent: {
    alignItems: 'center',
    gap: 12,
    paddingLeft: 82,
    paddingRight: 6,
    paddingTop: 12,
  },
  poolCardTitle: {
    color: '#f1f1f1',
    fontFamily: 'Ubuntu-Bold',
    fontSize: 23,
    letterSpacing: 0,
    lineHeight: 29,
    textAlign: 'center',
  },
  poolCardTime: {
    color: '#ffffff',
    fontFamily: 'Ubuntu-Regular',
    fontSize: 22,
    lineHeight: 28,
    textAlign: 'center',
  },
  poolCardFooter: {
    alignItems: 'flex-end',
    bottom: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
    left: 14,
    position: 'absolute',
    right: 14,
  },
  poolCardPrice: {
    color: '#d8d8d8',
    flex: 1,
    fontFamily: 'Ubuntu-Regular',
    fontSize: 14,
    lineHeight: 18,
    paddingRight: 8,
  },
  tickItButton: {
    alignItems: 'center',
    borderColor: '#e8e8e8',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 34,
    minWidth: 92,
    paddingHorizontal: 14,
  },
  tickItButtonText: {
    color: '#ffffff',
    fontFamily: 'Ubuntu-Bold',
    fontSize: 18,
    lineHeight: 23,
  },
  poolDetail: {
    gap: 14,
  },
  backButton: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: '#151515',
    borderColor: '#2a2a2a',
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 4,
    minHeight: 38,
    paddingLeft: 9,
    paddingRight: 13,
  },
  backButtonText: {
    color: '#ffffff',
    fontFamily: 'Ubuntu-Bold',
    fontSize: 11,
    letterSpacing: 0.8,
    lineHeight: 16,
  },
  poolHeader: {
    backgroundColor: '#070707',
    borderColor: '#151515',
    borderRadius: 0,
    borderWidth: 1,
    flexDirection: 'row',
    height: 58,
    overflow: 'hidden',
    position: 'relative',
  },
  poolSide: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 7,
    paddingHorizontal: 10,
  },
  poolSideRight: {
    justifyContent: 'flex-end',
    paddingRight: 16,
  },
  poolDivider: {
    backgroundColor: '#2a2a2a',
    height: '100%',
    width: 1,
  },
  poolAsset: {
    color: '#55555b',
    fontFamily: 'Ubuntu-Bold',
    fontSize: 13,
    letterSpacing: 1.2,
    lineHeight: 18,
  },
  poolPrice: {
    color: '#ff9d17',
    fontFamily: 'Ubuntu-Bold',
    fontSize: 23,
    letterSpacing: 0,
    lineHeight: 28,
  },
  poolPredictLabel: {
    color: '#68686f',
    fontFamily: 'Ubuntu-Bold',
    fontSize: 12,
    letterSpacing: 1.3,
    lineHeight: 17,
  },
  poolTimer: {
    color: '#ffffff',
    fontFamily: 'Ubuntu-Bold',
    fontSize: 23,
    letterSpacing: 0,
    lineHeight: 28,
  },
  poolAccent: {
    backgroundColor: '#211a34',
    height: '120%',
    position: 'absolute',
    right: -10,
    top: -6,
    transform: [{ skewX: '5deg' }],
    width: 20,
  },
  poolDetailBody: {
    alignItems: 'center',
    backgroundColor: '#090909',
    borderColor: '#262626',
    borderRadius: 22,
    borderWidth: 1,
    gap: 14,
    paddingHorizontal: 18,
    paddingVertical: 28,
  },
  poolLogoLarge: {
    alignItems: 'center',
    backgroundColor: '#111111',
    borderRadius: 24,
    borderWidth: 1,
    height: 86,
    justifyContent: 'center',
    width: 86,
  },
  poolLogoLargeText: {
    fontFamily: 'Ubuntu-Bold',
    fontSize: 44,
    lineHeight: 52,
  },
  poolLogoLargeImage: {
    height: 60,
    resizeMode: 'contain',
    width: 60,
  },
  poolDetailTitle: {
    color: '#ffffff',
    fontFamily: 'Ubuntu-Bold',
    fontSize: 26,
    lineHeight: 32,
    textAlign: 'center',
  },
  poolDetailMeta: {
    color: '#cfcfcf',
    fontFamily: 'Ubuntu-Regular',
    fontSize: 17,
    lineHeight: 23,
    textAlign: 'center',
  },
  priceChartCard: {
    alignItems: 'center',
    backgroundColor: '#0d0907',
    borderColor: '#241c17',
    borderRadius: 8,
    borderWidth: 1,
    gap: 14,
    overflow: 'hidden',
    paddingBottom: 16,
    paddingTop: 14,
  },
  priceChartTopRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    width: '100%',
  },
  priceChartAsset: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    minWidth: 70,
  },
  priceChartLogo: {
    height: 22,
    resizeMode: 'contain',
    width: 22,
  },
  priceChartSymbol: {
    color: '#77706c',
    fontFamily: 'Ubuntu-Bold',
    fontSize: 15,
    letterSpacing: 1.4,
    lineHeight: 20,
  },
  priceChartValue: {
    color: '#ff9d17',
    flex: 1,
    fontFamily: 'Ubuntu-Bold',
    fontSize: 32,
    letterSpacing: 0,
    lineHeight: 38,
    textAlign: 'right',
  },
  priceChartFeedStatus: {
    alignSelf: 'flex-start',
    color: '#77706c',
    fontFamily: 'Ubuntu-Medium',
    fontSize: 11,
    letterSpacing: 0.8,
    lineHeight: 15,
    marginTop: -8,
    paddingHorizontal: 14,
    textTransform: 'uppercase',
  },
  priceChartRoundRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: -4,
    paddingHorizontal: 14,
    width: '100%',
  },
  priceChartRoundText: {
    color: '#8f8985',
    fontFamily: 'Ubuntu-Medium',
    fontSize: 11,
    lineHeight: 15,
  },
  priceChart: {
    backgroundColor: '#120d09',
    overflow: 'hidden',
    position: 'relative',
  },
  priceChartGridLine: {
    backgroundColor: '#241c17',
    height: 1,
    left: 0,
    opacity: 0.85,
    position: 'absolute',
  },
  priceChartAxisRail: {
    backgroundColor: '#050505',
    height: '100%',
    position: 'absolute',
    top: 0,
    zIndex: 5,
  },
  priceChartAxisLabel: {
    color: '#aaa6a2',
    fontFamily: 'Ubuntu-Medium',
    fontVariant: ['tabular-nums'],
    fontSize: 13,
    lineHeight: 18,
    position: 'absolute',
    textAlign: 'left',
    zIndex: 6,
  },
  priceChartPhaseDivider: {
    backgroundColor: '#6a635c',
    height: '100%',
    position: 'absolute',
    top: 0,
    width: 1,
    zIndex: 7,
  },
  priceChartFutureZone: {
    backgroundColor: 'rgba(141, 107, 255, 0.18)',
    height: '100%',
    position: 'absolute',
    top: 0,
    zIndex: 1,
  },
  priceChartLayerLabel: {
    color: '#77706c',
    fontFamily: 'Ubuntu-Bold',
    fontSize: 13,
    letterSpacing: 1.2,
    lineHeight: 18,
    position: 'absolute',
    top: 14,
    zIndex: 8,
  },
  priceChartLayerLabelRight: {
    color: '#8d8395',
  },
  priceChartPredictLabel: {
    color: '#77706c',
    fontFamily: 'Ubuntu-Bold',
    fontSize: 13,
    letterSpacing: 1.2,
    lineHeight: 18,
    position: 'absolute',
    top: 14,
    zIndex: 4,
  },
  priceChartGuideLine: {
    borderColor: 'rgba(255, 157, 23, 0.48)',
    borderStyle: 'dashed',
    borderTopWidth: 1,
    height: 1,
    left: 0,
    position: 'absolute',
    zIndex: 3,
  },
  priceChartPredictionLine: {
    borderColor: 'rgba(184, 255, 102, 0.56)',
    borderStyle: 'dashed',
    borderTopWidth: 1,
    height: 1,
    left: 0,
    position: 'absolute',
    zIndex: 3,
  },
  priceChartSegment: {
    borderRadius: 999,
    height: 3.5,
    position: 'absolute',
    zIndex: 4,
  },
  priceChartSegmentGlow: {
    borderRadius: 999,
    height: 9,
    opacity: 0.16,
    position: 'absolute',
    zIndex: 3,
  },
  priceChartCurrentDot: {
    borderColor: 'rgba(255, 157, 23, 0.24)',
    borderRadius: 999,
    borderWidth: 8,
    height: 22,
    position: 'absolute',
    width: 22,
    zIndex: 8,
  },
  priceChartPredictionPill: {
    alignItems: 'center',
    backgroundColor: '#b8ff66',
    borderRadius: 999,
    minHeight: 38,
    justifyContent: 'center',
    paddingHorizontal: 14,
    position: 'absolute',
    zIndex: 9,
  },
  priceChartPredictionText: {
    color: '#000000',
    fontFamily: 'Ubuntu-Medium',
    fontSize: 14,
    lineHeight: 19,
  },
  priceChartPriceTag: {
    alignItems: 'center',
    borderRadius: 999,
    maxWidth: 132,
    minHeight: 34,
    minWidth: 76,
    justifyContent: 'center',
    paddingHorizontal: 12,
    position: 'absolute',
    right: 4,
    zIndex: 10,
  },
  priceChartPriceTagText: {
    color: '#000000',
    fontFamily: 'Ubuntu-Medium',
    fontVariant: ['tabular-nums'],
    fontSize: 14,
    lineHeight: 18,
  },
  tileButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(232, 255, 83, 0.82)',
    borderColor: 'rgba(255, 255, 255, 0.78)',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'absolute',
    zIndex: 12,
  },
  tileButtonPressed: {
    opacity: 0.86,
    transform: [{ scale: 0.98 }],
  },
  tileButtonSelected: {
    backgroundColor: '#b8ff66',
    borderColor: '#ffffff',
    borderWidth: 2,
    shadowColor: '#dfff63',
    shadowOpacity: 0.55,
    shadowRadius: 12,
  },
  tileButtonWinning: {
    backgroundColor: '#ffffff',
    borderColor: '#b8ff66',
  },
  tileButtonDisabled: {
    opacity: 0.38,
  },
  tileStakeText: {
    color: '#050505',
    fontFamily: 'Ubuntu-Bold',
    fontSize: 11,
    fontVariant: ['tabular-nums'],
    lineHeight: 13,
  },
  tileMultiplierText: {
    color: '#2f3220',
    fontFamily: 'Ubuntu-Medium',
    fontSize: 9,
    fontVariant: ['tabular-nums'],
    lineHeight: 11,
  },
  tileSummary: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 2,
    width: '100%',
  },
  tileSummaryItem: {
    backgroundColor: '#151515',
    borderColor: '#2a2a2a',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    minHeight: 46,
    minWidth: 92,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  tileSummaryItemWide: {
    backgroundColor: '#151515',
    borderColor: '#2a2a2a',
    borderRadius: 8,
    borderWidth: 1,
    minHeight: 46,
    paddingHorizontal: 10,
    paddingVertical: 7,
    width: '100%',
  },
  tileSummaryLabel: {
    color: '#77706c',
    fontFamily: 'Ubuntu-Bold',
    fontSize: 10,
    letterSpacing: 0.8,
    lineHeight: 14,
  },
  tileSummaryValue: {
    color: '#ffffff',
    fontFamily: 'Ubuntu-Bold',
    fontSize: 13,
    fontVariant: ['tabular-nums'],
    lineHeight: 18,
  },
  tileResultCard: {
    alignItems: 'center',
    backgroundColor: '#151515',
    borderColor: '#333333',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
    minHeight: 58,
    paddingHorizontal: 12,
    paddingVertical: 10,
    width: '100%',
  },
  tileResultTextGroup: {
    flex: 1,
    gap: 1,
  },
  tileResultLabel: {
    color: '#b8ff66',
    fontFamily: 'Ubuntu-Bold',
    fontSize: 11,
    letterSpacing: 1,
    lineHeight: 15,
  },
  tileResultValue: {
    color: '#ffffff',
    fontFamily: 'Ubuntu-Medium',
    fontSize: 14,
    fontVariant: ['tabular-nums'],
    lineHeight: 19,
  },
  claimButton: {
    alignItems: 'center',
    backgroundColor: '#b8ff66',
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 40,
    minWidth: 106,
    paddingHorizontal: 12,
  },
  claimButtonText: {
    color: '#000000',
    fontFamily: 'Ubuntu-Bold',
    fontSize: 13,
    letterSpacing: 0.8,
    lineHeight: 18,
  },
  predictionActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 8,
    width: '100%',
  },
  predictionButton: {
    alignItems: 'center',
    borderRadius: 8,
    flex: 1,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    minHeight: 52,
    paddingHorizontal: 12,
  },
  predictionButtonUp: {
    backgroundColor: '#b8ff66',
  },
  predictionButtonDown: {
    backgroundColor: '#222222',
    borderColor: '#474747',
    borderWidth: 1,
  },
  predictionButtonDisabled: {
    opacity: 0.58,
  },
  predictionButtonText: {
    color: '#000000',
    fontFamily: 'Ubuntu-Bold',
    fontSize: 17,
    lineHeight: 22,
    textTransform: 'uppercase',
  },
  predictionButtonTextLight: {
    color: '#ffffff',
  },
  predictionStatus: {
    color: '#d8d8d8',
    fontFamily: 'Ubuntu-Regular',
    fontSize: 13,
    lineHeight: 19,
    paddingHorizontal: 6,
    textAlign: 'center',
  },
  resultFeedbackOverlay: {
    alignItems: 'center',
    bottom: 0,
    justifyContent: 'center',
    left: 0,
    paddingHorizontal: 20,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 50,
  },
  resultFeedbackWin: {
    backgroundColor: 'rgba(63, 255, 118, 0.24)',
  },
  resultFeedbackLose: {
    backgroundColor: 'rgba(255, 45, 67, 0.26)',
  },
  resultFeedbackToast: {
    alignItems: 'center',
    backgroundColor: '#101413',
    borderColor: '#303a37',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    maxWidth: 360,
    minHeight: 74,
    paddingHorizontal: 16,
    paddingVertical: 13,
    width: '100%',
  },
  resultFeedbackToastWin: {
    borderColor: 'rgba(184, 255, 102, 0.62)',
    shadowColor: '#72ff5f',
    shadowOpacity: 0.26,
    shadowRadius: 18,
  },
  resultFeedbackToastLose: {
    borderColor: 'rgba(255, 107, 107, 0.62)',
    shadowColor: '#ff4a4a',
    shadowOpacity: 0.26,
    shadowRadius: 18,
  },
  resultFeedbackCopy: {
    flex: 1,
    gap: 2,
  },
  resultFeedbackTitle: {
    color: '#ffffff',
    fontFamily: 'Ubuntu-Bold',
    fontSize: 18,
    lineHeight: 23,
  },
  resultFeedbackMessage: {
    color: '#b8c2bf',
    fontFamily: 'Ubuntu-Regular',
    fontSize: 13,
    lineHeight: 18,
  },
  sheetBackdrop: {
    backgroundColor: 'rgba(0, 0, 0, 0.62)',
    flex: 1,
    justifyContent: 'flex-end',
  },
  walletSheet: {
    backgroundColor: '#111111',
    borderColor: '#2a2a2a',
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    borderWidth: 1,
    gap: 12,
    paddingBottom: 28,
    paddingHorizontal: 18,
    paddingTop: 10,
  },
  sheetHandle: {
    alignSelf: 'center',
    backgroundColor: '#4b4b4b',
    borderRadius: 999,
    height: 4,
    marginBottom: 6,
    width: 44,
  },
  sheetTitle: {
    color: '#ffffff',
    fontFamily: 'Ubuntu-Bold',
    fontSize: 20,
    letterSpacing: 0,
    lineHeight: 26,
  },
  fullAddress: {
    backgroundColor: '#191919',
    borderColor: '#2f2f2f',
    borderRadius: 8,
    borderWidth: 1,
    color: '#e6e6e6',
    fontFamily: 'Ubuntu-Regular',
    fontSize: 13,
    lineHeight: 19,
    padding: 12,
  },
  sheetAction: {
    alignItems: 'center',
    backgroundColor: '#1c1c1c',
    borderColor: '#303030',
    borderRadius: 8,
    borderWidth: 1,
    minHeight: 46,
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  sheetActionPrimary: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 8,
    flexDirection: 'row',
    gap: 8,
    minHeight: 48,
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  sheetActionPrimaryText: {
    color: '#000000',
    fontFamily: 'Ubuntu-Bold',
    fontSize: 14,
    letterSpacing: 0.8,
  },
  sheetActionText: {
    color: '#ffffff',
    fontFamily: 'Ubuntu-Bold',
    fontSize: 15,
    letterSpacing: 0,
  },
  sheetActionDanger: {
    alignItems: 'center',
    backgroundColor: '#2a1010',
    borderColor: '#5f2020',
    borderRadius: 8,
    borderWidth: 1,
    minHeight: 46,
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  sheetActionDangerText: {
    color: '#ff8f8f',
    fontFamily: 'Ubuntu-Bold',
    fontSize: 15,
    letterSpacing: 0,
  },
  sheetBodyText: {
    color: '#c8c8c8',
    fontFamily: 'Ubuntu-Regular',
    fontSize: 14,
    lineHeight: 20,
  },
  button: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 44,
    paddingHorizontal: 18,
    paddingVertical: 11,
  },
  buttonDisabled: {
    backgroundColor: '#333333',
  },
  buttonPressed: {
    opacity: 0.78,
    transform: [{ scale: 0.98 }],
  },
  buttonText: {
    color: '#000000',
    fontFamily: 'Ubuntu-Bold',
    fontSize: 15,
    letterSpacing: 0,
    lineHeight: 20,
  },
  buttonTextDisabled: {
    color: '#8f8f8f',
  },
  splash: {
    alignItems: 'center',
    backgroundColor: '#000000',
    flex: 1,
    justifyContent: 'center',
  },
  splashWord: {
    alignItems: 'center',
    alignSelf: 'center',
    flexDirection: 'row',
    gap: 6,
    justifyContent: 'center',
    transform: [{ translateX: 28 }],
    width: 174,
  },
  splashLogoMark: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 12,
    height: 56,
    justifyContent: 'center',
    width: 56,
  },
  splashLogoMarkText: {
    color: '#000000',
    fontFamily: 'Ubuntu-Bold',
    fontSize: 42,
    lineHeight: 48,
  },
  splashIckReveal: {
    overflow: 'hidden',
  },
  splashIck: {
    color: '#ffffff',
    fontFamily: 'Ubuntu-Bold',
    fontSize: 56,
    letterSpacing: 0,
    lineHeight: 64,
  },
})
